### ISSUE TITLE
[Help] - concurrency definition and how its supposed to work

### ISSUE THREAD

**Issue by ggahmed** [samrith-s/concurrent-tasks#2]
So ive been using this great library for a while to handle my tasks and i have to say it works great.
I'm starting to wonder what you mean by concurrency...As far as i understand it means running tasks in parallel... example : 

total tasks 10
concurrency: 3

on task add or start : 3 tasks will run at the same time and at any given time i should expect for this to run 3 tasks at the same time

reality : 

only one task is executed at a time and only after its completion the second task is added regardless of concurrency.

any help understanding this would be greatly appreciated

Here is my task runner config - even though ive set concurrency it defaults to 3 which is a nonissue because i dont think 3 tasks are being run at the same time either...

```
const TaskRunner = require("concurrent-tasks");

const runner = new TaskRunner({
  autoStart: true,

  setConcurrency: 10,

  onEnd({ duration: { total } }) {
    console.log(`✅   Completed all tasks in: ${(total / 1000).toFixed(2)}s`);
  },

  onDone({ completed, total }) {
    console.log(`✅ Completed ${completed} of ${total} tasks with ${runner.concurrency} concurrency`)

  }
});
```

**Comment by samrith-s** [comment]
Hey @ggahmed ,

I'm glad you're liking it. Yes, what you described is exactly what it's supposed to do.

So that's weird. From whatever tests I've run, it does run tasks as per concurrency. You can try out the demo. Alternatively, could you also post your "task"? What does it do? Does it call `done`?

And for concurrency, the key is `concurrency`, not `setConcurrency`.

Once you post your task, and probably a minimum reproducible repo, I can debug this for you. :)

**Comment by samrith-s** [comment]
Closing due to no response.

**Comment by PrinceS25** [comment]
I know I'm 2 years late but I have a similar issue. @ggahmed, if you've solved your issue and you remember what caused the problem, please do tell me.

**Comment by samrith-s** [comment]
@PrinceS25 Hey,couple of things:
- This issue is about v1 of this project
- Concurrency definition still pertains in the newer version 

Could you maybe add more description? Coz I don't understand this. Also, if you could try v2, it's maybe help understand better as it allows more hooks to tap into a task's lifecycle. :)
